# Generated by Django 2.2.16 on 2021-08-13 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021, message='Ты умеешь перемещаться в будущее? Введи верную дату)'), django.core.validators.MinValueValidator(1, message='Введи корректную дату, дата не может быть ниже года')], verbose_name='Год создания произведения'),
        ),
    ]
