# Generated by Django 2.2.6 on 2021-08-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210813_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='rating',
            new_name='score',
        ),
    ]
