# Generated by Django 2.2.6 on 2021-08-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210812_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='count',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='summ',
        ),
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='average',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
