# Generated by Django 2.2.6 on 2021-08-14 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_reviews_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
