# Generated by Django 2.2.6 on 2021-08-16 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20210816_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
