# Generated by Django 2.2.16 on 2021-08-18 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20210819_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Имя жанра'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2021, message='Ты умеешь перемещаться в будущее? Введи верную дату)'), django.core.validators.MinValueValidator(1, message='Введи корректную дату, дата не может быть ниже года')], verbose_name='Год создания произведения'),
        ),
    ]
